# Generated by Django 3.2.22 on 2023-12-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="cat_slug",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Слаг категории"),
        ),
    ]
