# Generated by Django 4.2.8 on 2025-05-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menuitem_cat_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu item', 'verbose_name_plural': 'Menu items'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_be',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='cat_slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='category slug '),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(max_length=255, verbose_name='link'),
        ),
    ]
