# Generated by Django 3.2.22 on 2023-11-25 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Категория статьи",
                "verbose_name_plural": "Категории статей",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="DeviceCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Категория устройства",
                "verbose_name_plural": "Категории устройств",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Devices",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name="URL")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="devices_img/", verbose_name="Фото устройства"),
                ),
                ("model", models.CharField(max_length=256, verbose_name="Модель устройства")),
                ("size", models.CharField(max_length=256, verbose_name="Размеры")),
                ("power", models.CharField(max_length=256, verbose_name="Питание")),
                ("protocol", models.CharField(max_length=256, verbose_name="Поддерживаемые протоколы передачи")),
                ("temperature", models.CharField(max_length=256, verbose_name="Рабочие температуры")),
                ("set", models.CharField(max_length=256, verbose_name="Комплект")),
                ("link_to_buy", models.CharField(max_length=256, verbose_name="Ссылка для покупки")),
                ("deleted", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="mainapp.devicecategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Устройство",
                "verbose_name_plural": "Устройства",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Platforms",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Платформа",
                "verbose_name_plural": "Платформы",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Scenarios",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                ("text", models.TextField(blank=True, verbose_name="Текст")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "images",
                    models.ImageField(blank=True, null=True, upload_to="scenarios_img/", verbose_name="Изображение"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата редактирования")),
                ("deleted", models.BooleanField(default=False)),
                ("devices", models.ManyToManyField(to="mainapp.Devices")),
            ],
            options={
                "verbose_name": "Сценарий",
                "verbose_name_plural": "Сценарии",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="devices",
            name="platforms",
            field=models.ManyToManyField(to="mainapp.Platforms"),
        ),
        migrations.CreateModel(
            name="Articles",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name="URL")),
                ("preambule", models.TextField(blank=True, verbose_name="Краткое описание")),
                ("text", models.TextField(blank=True, verbose_name="Текст")),
                (
                    "images",
                    models.ImageField(blank=True, null=True, upload_to="articles_img/", verbose_name="Изображение"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Edited")),
                ("deleted", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="mainapp.articlecategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["title"],
            },
        ),
    ]
