# Generated by Django 3.2.22 on 2023-12-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_auto_20231130_1850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name="URL"),
        ),
    ]
