# Generated by Django 3.2.22 on 2023-12-10 16:00

import autoslug.fields
from django.db import migrations, models

import mainapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_alter_articles_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="devices",
            name="foto2",
            field=models.ImageField(
                blank=True, null=True, upload_to=mainapp.models.device_foto_path, verbose_name="Фото устройства_2"
            ),
        ),
        migrations.AddField(
            model_name="devices",
            name="foto3",
            field=models.ImageField(
                blank=True, null=True, upload_to=mainapp.models.device_foto_path, verbose_name="Фото устройства_3"
            ),
        ),
        migrations.AddField(
            model_name="devices",
            name="foto4",
            field=models.ImageField(
                blank=True, null=True, upload_to=mainapp.models.device_foto_path, verbose_name="Фото устройства_4"
            ),
        ),
        migrations.AddField(
            model_name="devices",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to=mainapp.models.device_foto_path, verbose_name="Иконка_устройства"
            ),
        ),
        migrations.AlterField(
            model_name="devices",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, populate_from="title", verbose_name="URL"),
        ),
    ]
