# Generated by Django 3.2.22 on 2023-12-10 18:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_auto_20231210_1600"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlecategory",
            name="slug",
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from="title"),
        ),
        migrations.AddField(
            model_name="devicecategory",
            name="slug",
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from="title"),
        ),
    ]
