# Generated by Django 4.2.8 on 2024-05-01 19:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0012_rename_article_id_articlecomment_article_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
        migrations.RenameModel(
            old_name='Platforms',
            new_name='Platform',
        ),
        migrations.RenameModel(
            old_name='Scenarios',
            new_name='Scenario',
        ),
    ]
