# Generated by Django 4.2.8 on 2026-08-10 18:30

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0016_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['title'], 'verbose_name': 'Article category', 'verbose_name_plural': 'Article categories'},
        ),
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['title'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='devicecategory',
            options={'ordering': ['title'], 'verbose_name': 'Device category', 'verbose_name_plural': 'Device categories'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-time_create'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['title'], 'verbose_name': 'Idea', 'verbose_name_plural': 'Ideas'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['title'], 'verbose_name': 'Platform', 'verbose_name_plural': 'Platforms'},
        ),
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Rating star', 'verbose_name_plural': 'Rating stars'},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ['title'], 'verbose_name': 'Scenario', 'verbose_name_plural': 'Scenarios'},
        ),
        migrations.AlterModelOptions(
            name='scenariocomment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='mainapp.articlecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_10',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 10'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_11',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 11'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_12',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 12'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_13',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 13'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_14',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 14'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_15',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 15'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_16',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 16'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_17',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 17'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_18',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 18'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_19',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 19'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_20',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 20'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_21',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 21'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_22',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 22'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_23',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 23'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_24',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 24'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_25',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 25'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_5',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 5'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_6',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 6'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_7',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 7'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_8',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 8'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_9',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Picture 9'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.article_img_path, verbose_name='Main picture'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preambule',
            field=models.TextField(blank=True, verbose_name='Brief description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comment author'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='content',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Comment date'),
        ),
        migrations.AlterField(
            model_name='device',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='mainapp.devicecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='device',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.device_foto_path, verbose_name='Device photo 1'),
        ),
        migrations.AlterField(
            model_name='device',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.device_foto_path, verbose_name='Device photo 2'),
        ),
        migrations.AlterField(
            model_name='device',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.device_foto_path, verbose_name='Device photo 3'),
        ),
        migrations.AlterField(
            model_name='device',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.device_foto_path, verbose_name='Device photo 4'),
        ),
        migrations.AlterField(
            model_name='device',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.device_foto_path, verbose_name='Device icon'),
        ),
        migrations.AlterField(
            model_name='device',
            name='link_to_buy',
            field=models.CharField(max_length=256, verbose_name='Purchase link'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=256, verbose_name='Device model'),
        ),
        migrations.AlterField(
            model_name='device',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='mainapp.platform', verbose_name='Platforms'),
        ),
        migrations.AlterField(
            model_name='device',
            name='power',
            field=models.CharField(max_length=256, verbose_name='Power supply'),
        ),
        migrations.AlterField(
            model_name='device',
            name='protocol',
            field=models.CharField(max_length=256, verbose_name='Supported protocols'),
        ),
        migrations.AlterField(
            model_name='device',
            name='set',
            field=models.CharField(max_length=256, verbose_name='Package contents'),
        ),
        migrations.AlterField(
            model_name='device',
            name='size',
            field=models.CharField(max_length=256, verbose_name='Dimensions'),
        ),
        migrations.AlterField(
            model_name='device',
            name='temperature',
            field=models.CharField(max_length=256, verbose_name='Operating temperature'),
        ),
        migrations.AlterField(
            model_name='device',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Sender IP'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sender name'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sent at'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.scenario', verbose_name='Scenario'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ratingstar', verbose_name='Star'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_10',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 10'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_11',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 11'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_12',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 12'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_13',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 13'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_14',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 14'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_15',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 15'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_16',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 16'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_17',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 17'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_18',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 18'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_19',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 19'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_20',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 20'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_21',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 21'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_22',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 22'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_23',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 23'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_24',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 24'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_5',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 5'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_6',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 6'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_7',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 7'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_8',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 8'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='img_9',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Image 9'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Main image'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scheme',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.scenarios_img_path, verbose_name='Scheme'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='scenariocomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comment author'),
        ),
        migrations.AlterField(
            model_name='scenariocomment',
            name='content',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='scenariocomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Comment date'),
        ),
        migrations.AlterField(
            model_name='scenariocomment',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.scenario', verbose_name='Scenario'),
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_types', to='mainapp.devicecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Device type',
                'verbose_name_plural': 'Device types',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='mainapp.devicetype', verbose_name='Device type'),
        ),
    ]
