# Generated by Django 4.2.8 on 2026-08-12 19:23

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_purchaselink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceimage',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='deviceimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deviceimage',
            name='image',
            field=models.ImageField(upload_to=mainapp.models.device_image_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='purchaselink',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_links', to='mainapp.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='purchaselink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
