# Generated by Django 4.2.8 on 2026-08-16 19:38

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_scenarioimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='platform',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to=mainapp.models.article_img_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ecosystem',
            field=models.ManyToManyField(blank=True, to='mainapp.platform', verbose_name='Ecosystem'),
        ),
        migrations.AlterField(
            model_name='device',
            name='protocols',
            field=models.ManyToManyField(blank=True, to='mainapp.protocol', verbose_name='Supported protocols'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='title',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scenarioimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ScenarioVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_variants', to='mainapp.platform', verbose_name='Platform')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='mainapp.scenario', verbose_name='Scenario')),
            ],
            options={
                'verbose_name': 'Scenario variant',
                'verbose_name_plural': 'Scenario variants',
                'unique_together': {('scenario', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='RequiredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Quantity')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.device', verbose_name='Device')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.devicetype', verbose_name='Device type')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_devices', to='mainapp.scenariovariant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Required device',
                'verbose_name_plural': 'Required devices',
            },
        ),
    ]
