# Generated by Django 4.2.8 on 2026-08-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_remove_scenario_platform_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['deleted', '-created_at'], name='mainapp_sce_deleted_e7a0d4_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['author', 'deleted'], name='mainapp_sce_author__cd481e_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['deleted', 'created_at'], name='mainapp_sce_deleted_6ac438_idx'),
        ),
    ]
