# Generated by Django 4.2.8 on 2026-08-20 12:00

import django.db.models.deletion
from django.db import migrations, models


def delete_required_devices_without_device(apps, schema_editor):
    """Удалить записи RequiredDevice, где device не был задан (был только device_type)."""
    RequiredDevice = apps.get_model('mainapp', 'RequiredDevice')
    RequiredDevice.objects.filter(device__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_alter_scenario_created_at_alter_scenario_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requireddevice',
            name='device_type',
        ),
        migrations.RunPython(
            delete_required_devices_without_device,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='requireddevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.device', verbose_name='Device'),
        ),
    ]