# Generated by Django 4.2.8 on 2026-09-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_scenario_device_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='Mark vintage devices that are no longer sold', verbose_name='Legacy'),
        ),
    ]
