# Generated by Django 3.2.22 on 2023-12-10 16:00

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0002_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Такой пользователь уже существует"},
                help_text="Используйте только буквы, цифры или знаки @/./+/-/_",
                max_length=15,
                unique=True,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
