# Generated by Django 4.2.8 on 2023-12-24 15:48

import django.contrib.auth.validators
from django.db import migrations, models

import authapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0003_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=authapp.models.users_avatars_path),
        ),
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Такой пользователь уже существует"},
                help_text="Максимальное значение 15 символов. Используйте только буквы, цифры или знаки +/-/_",
                max_length=15,
                unique=True,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
                verbose_name="Мянушка(login)",
            ),
        ),
    ]
