# Generated by Django 4.2.8 on 2023-12-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0004_remove_user_last_name_user_avatar_user_birthday_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birthday",
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
