# Generated by Django 4.2.8 on 2024-05-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_rename_articles_article_rename_devices_device_and_more'),
        ('authapp', '0008_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='devices', to='mainapp.device', verbose_name='Устройства'),
        ),
    ]
