# Generated by Django 4.2.8 on 2025-03-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_user_email_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verify',
            new_name='is_active',
        ),
    ]
