# Generated by Django 4.2.8 on 2025-05-04 19:32

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models

import authapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_feedback'),
        ('authapp', '0014_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=authapp.models.users_avatars_path, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='devices',
            field=models.ManyToManyField(blank=True, to='mainapp.device', verbose_name='devices'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email address already exists.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, help_text='The author can add articles to the site', verbose_name='author status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only', max_length=15, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
